
version: 2

models:
  - name: table_to_model
    description: "A starter dbt model"
    columns:
      - name: user_id
        description: "user id"
        tests:
          - not_null

sources:
  - name: raw_data
    description: "machine learning raw tables"
    database: mlops
    schema: raw_data
    tables:
      - name: scores
      - name: movies
      - name: users